name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 18
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '18-ea'
    - name: Build with Maven
      run: ./mvnw -B clean package
